### ISSUE TITLE
Dirty fields

### ISSUE THREAD

**Issue by ekafyi** [svelteschool/svelte-forms#15]
Can we check whether the inputs have been touched (are "dirty") or do we have to do it outside of the library?

Thanks!

**Comment by kevmodrome** [comment]
You'll have to do that outside the library. If you have some ideas on how to add that functionality I'm open to PRs! :)

**Comment by ekafyi** [comment]
Thank you for the answer @kevmodrome. 

Was pressed for time so went with a slightly larger lib which already has the functionalities i needed (svelte-use-form). Hope to go back to svelte-forms in the future and maybe propose a PR!
