### ISSUE TITLE
The input radio it's not working

### ISSUE THREAD

**Issue by danierdev** [svelteschool/svelte-forms#2]
#### Issue description
First at all thanks for the library, this clean approach is really cool and flexible. Using the REPL demo with radio inputs i found a little bug.

#### Steps to reproduce the issue

1.  Add radio inputs for gender select
2. Select a value from radio list
3. Then select other value

#### What's the expected result?
```javascript
{
 "gender": "male",
 "topping": "Cream"
}
```

#### What's the actual result?
```javascript
{
 "gender": [
  "male"
 ],
 "topping": "Cream"
}
```

#### Additional details / screenshot

- [REPL](https://svelte.dev/repl/ff67b15eddfa4f878ec6065bc083f2c9?version=3.21.0)

**Comment by kevmodrome** [comment]
Thanks for the report. I'll take a look.
